default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mail-app_development

test: &test
  <<: *default
  database: mail-app_test

production:
  <<: *default
  database: mail-app_production
  password: <%= ENV['MAIL-APP_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
